// Code generated by counterfeiter. DO NOT EDIT.
package imagefakes

import (
	"sync"

	"code.cloudfoundry.org/windows2016fs/image"
	"github.com/opencontainers/image-spec/specs-go/v1"
)

type FakeMetadataReader struct {
	ReadStub        func() (v1.Manifest, v1.Image, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct{}
	readReturns     struct {
		result1 v1.Manifest
		result2 v1.Image
		result3 error
	}
	readReturnsOnCall map[int]struct {
		result1 v1.Manifest
		result2 v1.Image
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMetadataReader) Read() (v1.Manifest, v1.Image, error) {
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct{}{})
	fake.recordInvocation("Read", []interface{}{})
	fake.readMutex.Unlock()
	if fake.ReadStub != nil {
		return fake.ReadStub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.readReturns.result1, fake.readReturns.result2, fake.readReturns.result3
}

func (fake *FakeMetadataReader) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakeMetadataReader) ReadReturns(result1 v1.Manifest, result2 v1.Image, result3 error) {
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 v1.Manifest
		result2 v1.Image
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMetadataReader) ReadReturnsOnCall(i int, result1 v1.Manifest, result2 v1.Image, result3 error) {
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 v1.Manifest
			result2 v1.Image
			result3 error
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 v1.Manifest
		result2 v1.Image
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMetadataReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMetadataReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ image.MetadataReader = new(FakeMetadataReader)
